"""User is_active field type changed to BOOLEAN

Revision ID: 48e0483399f8
Revises: dd8becaabc7e
Create Date: 2025-02-17 17:30:12.905790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48e0483399f8"
down_revision: Union[str, None] = "dd8becaabc7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "is_active",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.BOOLEAN(),
        existing_nullable=True,
        postgresql_using="is_active::boolean",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "is_active",
        existing_type=sa.BOOLEAN(),
        type_=sa.VARCHAR(length=32),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
