"""blog model with blog_catg_relation added

Revision ID: e4f0a68d0e82
Revises: cdd8494a5f6f
Create Date: 2024-09-18 12:08:04.549270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f0a68d0e82'
down_revision: Union[str, None] = 'cdd8494a5f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('blog_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('view', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('blog_catg_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['blog_catg_id'], ['blog_category.blog_catg_id'], ),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_index(op.f('ix_blog_blog_id'), 'blog', ['blog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_blog_id'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
