"""blog user relationship added

Revision ID: eac67023ccdd
Revises: e4f0a68d0e82
Create Date: 2024-09-23 19:48:51.310152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac67023ccdd'
down_revision: Union[str, None] = 'e4f0a68d0e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'blog', 'user', ['author_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'author_id')
    # ### end Alembic commands ###
